# This is a basic workflow to help you get started with Actions

name: BUILD_EPI_IMAGES

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'EPI version'
        required: true
        default: '1.0.0-default'
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: github-actions-tests

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Setup Node version
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # running the build script 
      - name: build-images
        run: |
             chmod +x images/epi/build.sh
             images/epi/build.sh
        env:
          VERSION: ${{github.event.inputs.version}}
          
      - name: testing-build-ouptut
        run: docker image list
